version: "3.3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mydb-db:/var/lib/mysql

volumes:
  mydb-db: